name: KitPvP
author: Cervinakuy
main: com.planetgallium.kitpvp.Game
version: 2.2.3
description: The ultimate all-in-one KitPvP plugin.
website: https://www.spigotmc.org/resources/27107/
softdepend: [PlaceholderAPI, WorldGuard, Vault]
api-version: 1.13

commands:
   kitpvp:
     description: Main command.
     aliases: [kp, kit-pvp]
   ckit:
     description: Select a kit.
   cspawn:
     description: Teleports you to the spawn.
   ckits:
     description: View all available kits.
   cstats:
     description: View your stats.